sudo: true
language: python

python:
  - 2.7
  - 3.6

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install g++-4.9 -y -qq
  - pip install numpy

install: make CXX=g++-4.9 && sudo make install

script: make test

notifications:
  email: false
